sudo: required

language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION="6.10.1"

services:
  - docker

# travis-cli apparently has nvm, so we can use that
before_install:
  #NVM
  - nvm install $NODE_VERSION
  - node --version
  # Show current version of docker-compose
  - docker-compose pull
  - docker-compose build
  - docker ps -a
  - docker-compose up -d 
  # Run tests
 

script:
  - docker exec sharedev bash -c "cd /usr/src/app/ && mvn test -B"

  # - export CHROME_BIN=chromium-browser
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  # - sudo apt-get install -y libappindicator1 fonts-liberation
  # - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  # - sudo dpkg -i google-chrome*.deb

  # Show current version of docker-compose
  - docker-compose pull
  - docker-compose build
  - docker ps -a
  - docker-compose up -d  

script:
  - docker exec sverea bash -c "make db-init && make test"
