sudo: required

language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION="6.10.1"

services:
  - docker

addons:
  sonarcloud:
    organization: "dat265"
    token:
      secure: $sonar
    github_token:
      secure: $github
    branches:
      - master
      - develop

cache:
  directories:
    - "frontend/web/node_modules"
    - '$HOME/.m2'


# travis-cli apparently has nvm, so we can use that
before_install:
  #NVM
  - nvm install $NODE_VERSION
  - node --version

script:

  # - export CHROME_BIN=chromium-browser
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  # - sudo apt-get install -y libappindicator1 fonts-liberation
  # - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  # - sudo dpkg -i google-chrome*.deb

  # run sonar
  - sonar-scanner

  # Show current version of docker-compose
  - docker-compose pull
  - docker-compose build
  - docker ps -a
  - docker-compose up -d

  #docker exec -it sverea bash

  - docker exec sverea bash -c "make db-init && make install && make test"
