BEGIN;
DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS physicalpart;
DROP TABLE IF EXISTS physicalprint;

DROP TABLE IF EXISTS magicspairing;
DROP TABLE IF EXISTS digitalprintdata;
DROP TABLE IF EXISTS orderedpart;
DROP TABLE IF EXISTS digitalpart;
DROP TABLE IF EXISTS "order";
DROP TABLE IF EXISTS customer;

COMMIT;
